version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
