name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  expire-in-days:
    description: 'Number of days version is valid'
    required: true
    default: '7'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
